esphome:
  name: esp-greenhouse
  friendly_name: ESP Greenhouse

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "*****"

ota:
  - platform: esphome
    password: "****"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Make sure to setup these secrets! These are your home wifi credentials
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Gewachshaus Fallback Hotspot"
    password: "*****"

captive_portal:
    
#Busconfig
one_wire:
  - platform: gpio
    pin: GPIO1

#I2C config
i2c:
  sda: GPIOXX
  scl: GPIOXX
  scan: true
  id: bus_a

# UART config
uart:
  tx_pin: GPIOXX
  rx_pin: GPIOXX
  baud_rate: 9600

#only_temp
sensor:
  - platform: dallas_temp
    address: 0x1234567890123456
    name: temperature_ds18b20_1
    update_interval: 60s
  - platform: dallas_temp
    address: 0x1234567890123456
    name: temperature_ds18b20_2
    update_interval: 60s
  - platform: dht
    pin: GPIO10
    temperature:
      name: temperature_dht22
    humidity:
      name: humidity_dht22
    model: DHT22
    # accuracy_decimals: 1
    update_interval: 60s
  - platform: adc
    pin: GPIO4
    accuracy_decimals: 1
    unit_of_measurement: '%'
    attenuation: auto
    filters: 
      - calibrate_linear: 
        - 2.53 -> 100.0
        - 3.14 -> 0
    name: bodenfeuchtigkeit_1
    update_interval: 60s
  # - platform: adc
  #   pin: GPIO4
  #   accuracy_decimals: 5
  #   attenuation: auto
  #   name: bodenfeuchtigkeit_1_raw
  #   update_interval: 5s
  - platform: adc
    pin: GPIO5
    accuracy_decimals: 1
    unit_of_measurement: '%'
    attenuation: auto
    filters: 
      - calibrate_linear: 
        - 2.53 -> 100.0
        - 3.14 -> 0
    name: bodenfeuchtigkeit_2
    update_interval: 60s
  # - platform: adc
  #   pin: GPIO5
  #   accuracy_decimals: 5
  #   attenuation: auto
  #   name: bodenfeuchtigkeit_1_raw
  #   update_interval: 5s
  - platform: adc
    pin: GPIO6
    accuracy_decimals: 1
    unit_of_measurement: '%'
    attenuation: auto
    filters: 
      - calibrate_linear: 
        - 2.53 -> 100.0
        - 3.14 -> 0
    name: bodenfeuchtigkeit_3
    update_interval: 60s
    # - platform: adc
    #   pin: GPIO6
    #   accuracy_decimals: 5
    #   attenuation: auto
    #   name: bodenfeuchtigkeit_1_raw
    #   update_interval: 5s
  - platform: adc
    pin: GPIO7
    accuracy_decimals: 1
    unit_of_measurement: '%'
    attenuation: auto
    filters: 
      - calibrate_linear: 
        - 2.53 -> 100.0
        - 3.14 -> 0
    name: bodenfeuchtigkeit_4
    update_interval: 60s
    # - platform: adc
    #   pin: GPIO7
    #   accuracy_decimals: 5
    #   attenuation: auto
    #   name: bodenfeuchtigkeit_1_raw
    #   update_interval: 5s
  - platform: bh1750
    name: "BH1750_illuminance"
    address: 0x23
    update_interval: 60s
  - platform: mhz19
    co2:
      name: MH-Z19_CO2_value
    temperature:
      name: MH-Z19_temperature

binary sensor:
  - platform: gpio
    pin: GPIO19
    name: "door_contact"
    device_class: door
    update_interval: 60s
  - platform: gpio
    pin: GPIO20
    name: "window_contact_1"
    device_class: window
    update_interval: 60s
  - platform: gpio
    pin: GPIO21
    name: "window_contact_1"
    device_class: window
    update_interval: 60s

#Relais
switch:
  - platform: gpio
    pin: GPIO15
    name: "Relay 1"
  - platform: gpio
    pin: GPIO16
    name: "Relay 2"
  - platform: gpio
    pin: GPIO17
    name: "Relay 3"
  - platform: gpio
    pin: GPIO18
    name: "Relay 4"

